name: update-covid-19-repo

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '00 23 * * *' # at 23:00

jobs:
  covid-19-update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        R: [ '4.0.3' ]
    name: Updating on R ${{ matrix.R }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
          
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install r dependencies
        run: |
           install.packages(c("dplyr", "readr", "magrittr", "ggplot2", "RcppRoll", "gghighlight", "rmarkdown", "scales"))
        shell: Rscript {0}
        
      - name: Process data from nyt 
        run: |
          source('./scripts/process_covid_data_from_nyt.R')
        shell: Rscript {0}        
        
      - name: Plot data from nyt
        run: |
          source('./scripts/plot_covid_data_from_nyt.R')
        shell: Rscript {0}
        
      - name: Process data from cdc 
        run: |
          source('./scripts/process_covid_data_from_nyt.R')
        shell: Rscript {0}  
        
      - name: Render readme
        run: |
          source('./scripts/update_readme.R')
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated repo
